manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: krikun98
      url-base: https://github.com/krikun98
  projects:
    - name: zmk
      remote: krikun98
      revision: mouse-prototype
      import: app/west.yml
  self:
    path: config
